service-clip:
  handler: run.run
  module: modules/services/clip
  timeout: 30
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - ClipQueue
            - Arn
        batchSize: 1
  package:
    include:
      - modules/services/clip/run.py
      - modules/services/clip/helpers.py
      - libs/ffprobe

service-montage:
  handler: run.run
  module: modules/services/montage
  timeout: 30
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - MontageQueue
            - Arn
        batchSize: 1
  package:
    include:
      - modules/services/montage/run.py

service-stream-segment:
  handler: run.run
  module: modules/services/stream_segment
  memorySize: 1024
  timeout: 180
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - StreamSegmentQueue
            - Arn
        batchSize: 1
  package:
    include:
      - modules/services/stream_segment/run.py
      - libs/ffmpeg
      - libs/ffprobe

