service-clip:
  handler: run.run
  module: modules/clip
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.clip.name}
        batchSize: 1
  package:
    include:
      - modules/clip/run.py
      - modules/clip/helpers.py
      - libs/ffprobe

service-stream-initialize:
  handler: run.run
  module: modules/stream_initialize
  memorySize: 512
  timeout: 300
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream-initialize.name}
        batchSize: 1
  package:
    include:
      - modules/stream_initialize/run.py
      - libs/ffprobe

service-stream-segment-download:
  handler: run.run
  module: modules/stream_segment_download
  memorySize: 1024
  timeout: 180
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream-segment-download.name}
        batchSize: 1
  package:
    include:
      - modules/stream_segment_download/run.py
      - libs/ffmpeg
      - libs/ffprobe

