service--clip:
  handler: run.run
  module: modules/clip
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.clip.name}
        batchSize: 1
  package:
    include:
      - modules/clip/run.py

service--media--postprocess:
  handler: run.run
  module: modules/media__postprocess
  memorySize: 128
  timeout: 30
  events:
    - cloudwatchEvent:
        event:
          source:
            - aws.mediaconvert
          detail:
            status:
              - COMPLETE
              - ERROR
  package:
    include:
      - modules/media__postprocess/run.py

service--montage:
  handler: run.run
  module: modules/montage
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.montage.name}
        batchSize: 1
  package:
    include:
      - modules/montage/run.py

service--stream--analyze:
  handler: run.run
  module: modules/stream__analyze
  memorySize: 512
  timeout: 300
  reservedConcurrency: 5
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream--analyze.name}
        batchSize: 1
  package:
    include:
      - modules/stream__analyze/run.py


service--stream--initialize:
  handler: run.run
  module: modules/stream__initialize
  memorySize: 512
  timeout: 300
  reservedConcurrency: 5
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream--initialize.name}
        batchSize: 1
  package:
    include:
      - modules/stream__initialize/run.py
      - libs/ffprobe

service--stream-segment--analyze:
  handler: run.run
  module: modules/stream_segment__analyze
  memorySize: 1024
  timeout: 300
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream-segment--analyze.name}
        batchSize: 1
  package:
    include:
      - modules/stream_segment__analyze/run.py
      - libs/ffmpeg
      - libs/tesseract/**

service--stream-segment--download:
  handler: run.run
  module: modules/stream_segment__download
  memorySize: 1024
  timeout: 300
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.aws.region}:${self:custom.config.aws.account-id}:${self:custom.config.aws.sqs.stream-segment--download.name}
        batchSize: 1
  package:
    include:
      - modules/stream_segment__download/run.py
