service-clip:
  handler: run.run
  module: modules/clip
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:589344262905:ts-clip
        batchSize: 1
  package:
    include:
      - modules/clip/run.py
      - modules/clip/helpers.py
      - libs/ffprobe

service-stream-segment-download:
  handler: run.run
  module: modules/stream_segment_download
  memorySize: 1024
  timeout: 180
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:589344262905:ts-stream-segment-download
        batchSize: 1
  package:
    include:
      - modules/stream_segment_download/run.py
      - libs/ffmpeg
      - libs/ffprobe

