service--clip:
  handler: modules/clip/run.run
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.region}:${self:custom.config.account-id}:${self:custom.config.sqs.queues.clip.name}-${self:custom.config.stage}
        batchSize: 1

service--media--postprocess:
  handler: modules/media__postprocess/run.run
  memorySize: 128
  timeout: 30
  events:
    - cloudwatchEvent:
        event:
          source:
            - aws.mediaconvert
          detail:
            status:
              - COMPLETE
              - ERROR

service--montage:
  handler: modules/montage/run.run
  memorySize: 256
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.region}:${self:custom.config.account-id}:${self:custom.config.sqs.queues.montage.name}-${self:custom.config.stage}
        batchSize: 1

service--stream--analyze:
  handler: modules/stream__analyze/run.run
  memorySize: 512
  timeout: 300
  reservedConcurrency: 5
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.region}:${self:custom.config.account-id}:${self:custom.config.sqs.queues.stream--analyze.name}-${self:custom.config.stage}
        batchSize: 1

service--stream-segment--download:
  handler: modules/stream_segment__download/run.run
  memorySize: 1024
  timeout: 300
  events:
    - sqs:
        arn: arn:aws:sqs:${self:custom.config.region}:${self:custom.config.account-id}:${self:custom.config.sqs.queues.stream-segment--download.name}-${self:custom.config.stage}
        batchSize: 1
