service-clip:
  handler: run.run
  module: modules/clip
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:589344262905:ts-clip
        batchSize: 1
  package:
    include:
      - modules/clip/run.py
      - modules/clip/helpers.py
      - libs/ffprobe

service-montage:
  handler: run.run
  module: modules/montage
  timeout: 30
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:589344262905:ts-montage
        batchSize: 1
  package:
    include:
      - modules/montage/run.py

service-stream-segment:
  handler: run.run
  module: modules/stream_segment
  memorySize: 1024
  timeout: 180
  events:
    - sqs:
        arn: arn:aws:sqs:us-west-1:589344262905:ts-stream-segment-download
        batchSize: 1
  package:
    include:
      - modules/stream_segment/run.py
      - libs/ffmpeg
      - libs/ffprobe

